version: '3'
services:
  app:
    image: python:3.6
    volumes:
      # Aplicacao 
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8000:8000
    depends_on:
      - queue
  queue:
    image: redis:3.2
    networks: 
      - fila
  worker:
    build: worker
    environment: 
      - ENV_ESCALA=DEV
    volumes:
     # Escala
      - ./worker:/worker
    working_dir: /worker
    command: run.py
    networks: 
      - fila
    depends_on: 
      - queue
